### ISSUE TITLE
整数溢出bug更改

### ISSUE THREAD

**Issue by zn66665** [xiaoyuanxun/IndustryPreDemo#1]
#Bug描述：
当对某一个批次产品进行入库时，会调用getCanEnterStorge（）函数对入库的批次ID进行一次检查。实现如下：
 function getCanEnterStorge(string memory _modeNumber) internal view returns(bool){
        console.log('batchsLen[_modeNumber] = ', batchsLen[_modeNumber]);
        **uint256 lastBatch = batchs[_modeNumber][batchsLen[_modeNumber]-1];
        if(batchsLen[_modeNumber]==0) return true;
        uint256 lastBatch = batchs[_modeNumber][batchsLen[_modeNumber]-1];
        console.log('lastBatch = ', lastBatch);
        console.log('the result = ', components[lastBatch][rootCompIndex].state==State.Finish);
        return(components[lastBatch][rootCompIndex].state==State.Finish);
    }
不难发现，在**标记行，如果该型号首个批次下，由于在初始化时值为0，这里的batchs[_modeNumber][batchsLen[_modeNumber]-1];会产生溢出，是的该函数调用失败，固无法成功执行。建议修改为如下代码：
 function getCanEnterStorge(string memory _modeNumber) internal view returns(bool){
        console.log('batchsLen[_modeNumber] = ', batchsLen[_modeNumber]);
      //修改处
        uint256 lastBatch = 0;
        if(batchsLen[_modeNumber]==0) return true;
        uint256 lastBatch = batchs[_modeNumber][batchsLen[_modeNumber]-1];
        console.log('lastBatch = ', lastBatch);
        console.log('the result = ', components[lastBatch][rootCompIndex].state==State.Finish);
        return(components[lastBatch][rootCompIndex].state==State.Finish);
    }
由于没所有批次在第一次入库时值为0，就不用单独计算了，直接使他为0.

**Comment by xiaoyuanxun** [comment]
谢谢你的建议，我将采纳。
